module.exports = [
  'nme.com',
  'maisonkitsune',
  'bbc_playlister',
  'filtr',
  'diplomaddecent',
  'rockstargames',
  'daniel',
  'capitolrecords',
  'holgerchristoph',
  'bluenoterecords',
  'rsedit',
  'sfjazz_playlists',
  'thegrammys',
]
